In [145]:
import xlns as xl
import numpy as np
import torch
import tensorflow as tf

We start out with two Python lists containing the usual float64 values

In [146]:
x = [2.0, 3.0]
y = [4.0, 5.0]

We convert these to the xlns format format within a numpy array (xlns) and we are able to perform elementwise multiplication in xlnsnp format

In [147]:
x_xl = xl.xlnsnp(x)
y_xl = xl.xlnsnp(y)
print(x_xl*y_xl)

[xlns(7.999999984266906) xlns(15.000000326665468)]


We are also able to perform elementwise multiplication in numpy containing float64 format

In [148]:
x_np = np.array(x)
y_np = np.array(y)
print(x_np.dtype)
print(x_np*y_np)

float64
[ 8. 15.]


We are also able to perform elementwise multiplication as torch tensors, but in this case it converts to float32 automatically

In [149]:
x_torch = torch.tensor(x)
y_torch = torch.tensor(y)
print(x_torch.dtype)
print(x_torch*y_torch)

torch.float32
tensor([ 8., 15.])


We are also able to perform elementwise multiplication as tensorflow tensors, and in this case we can see that float32 is also used

In [150]:
x_tf = tf.constant(x)
y_tf = tf.constant(y)
print(x_tf*y_tf)

tf.Tensor([ 8. 15.], shape=(2,), dtype=float32)


When we wrap our xlnsnp arrays within a numpy array we can see that it is still possible with this nested numpy array setup, to perform elemenwise multiplication
using the xlns data format

In [151]:
x_npxl = np.array(x_xl)
y_npxl = np.array(y_xl)
print(x_npxl*y_npxl)

[xlnsnp(7.999999984266906) xlnsnp(15.000000326665468)]


When we use the numpy arrays within our xlnsnp data format it remains unchanged from starting with Python lists, and elementwise multiplication may still be performed

In [152]:
x_xlnp = xl.xlnsnp(x_np)
y_xlnp = xl.xlnsnp(y_np)
print(x_xlnp*y_xlnp)

[xlns(7.999999984266906) xlns(15.000000326665468)]


Demonstrates that when we attempt to convert directly from tensorflow into PyTorch we get an error message (some additional information)

In [153]:
try:
    x_torchtf = torch.tensor(x_tf)
    y_torchtf = torch.tensor(y_tf)
    print(x_torchtf*y_torchtf)
except TypeError as e:
    print(e)

Scalar tensor has no `len()`


Demonstrates that when we attempt to convert from a PyTorch tensor,
if we use an explicit converstion from constant data formats then we can turn this into a tensorflow tensor

In [154]:
x_tftorch = tf.constant(x_torch)
y_tftorch = tf.constant(y_torch)
print(x_tftorch*y_tftorch)

tf.Tensor([ 8. 15.], shape=(2,), dtype=float32)


Shows that when we attempt to use the xlnsnp format as a torch tensor and perform elementwise multiplication that an AttributeError is thrown as numpy.int64 datatype is expected

In [155]:
try:
    x_torchxl = torch.tensor(x_xl)
    y_torchxl = torch.tensor(y_xl)
    print(x_torchxl*y_torchxl)
except AttributeError as e:
    print(e)

'numpy.int64' object has no attribute '__len__'


Shows that when we attempt to use the xlnsnp format as a tensorflow tensor by converting from an expected constant data format, that it expects numpy.int64 again
and will not perform the elementwise multiplication

In [156]:
try:
    x_tfxl= tf.constant(x_xl)
    y_tfxl = tf.constant(y_xl)
    print(x_tfxl*y_tfxl)
except ValueError as e:
    print(e)

AttributeError: 'numpy.int64' object has no attribute '__len__'
Traceback (most recent call last):

  File "/home/jasmine/Documents/JupyterProjects/log_number_system_alaska/.xlns-env/lib/python3.10/site-packages/xlns.py", line 819, in __len__
    return self.nd.__len__()

AttributeError: 'numpy.int64' object has no attribute '__len__'. Did you mean: '__le__'?




Conclusion:
Numpy is able to support use of the xlns number system throughout, but PyTorch and Tensorflow are both unable to.

It appears that when attempting to directly use the xlnsnp number format and convert this to PyTorch and Tensorflow tensors, that numpy 64 bit integers are expected so the conversion cannot be applied.

It appears that when we create tensors directly using the initial Python list containing 64 bit floats